### ISSUE TITLE
Replace Material.getItemTransitionKey() with a stable method

### ISSUE THREAD

**Issue by choyatv** [DoubleDeltas/MineCollector#7]
![image](https://user-images.githubusercontent.com/123820469/234569215-aa674b98-fdc0-4395-b8d1-3fd9c1f018c0.png)

**Comment by DoubleDeltas** [comment]
제보 감사합니다!
해당 문제는 이미 제보된 사항으로 paper의 일부 버전에서 메소드 지원하지 않아 발생하는 것으로 확인되었습니다.
오늘 중으로 수정된 버전을 릴리즈하겠습니다!

**Comment by DoubleDeltas** [comment]
@choyatv 
죄송합니다! 제보하신 이슈는 현재로썬 해결하기 힘들어보입니다.
가급적 빠른 시일 내에 해결하겠습니다!

최신 버전의 Spigot 또는 Paper 버전을 사용하면 해당 이슈가 발생하지 않습니다! 참고 바랍니다.
